name: Drive Notes Sync

on:
  schedule:
    # - cron: "0 */3 * * *"  # Runs every 3 hours
    - cron: "*/1 * * * *"   # ✅ Every 1 minute
  workflow_dispatch:       # Allow manual run

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
      GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
      GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch PDFs from Google Drive
        run: python scripts/upload_notes.py

      - name: Merge / Organize / Rename PDFs
        run: python scripts/upload_notes.py

      - name: Commit & Push changes
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Auto-sync notes from Drive"
          git push

